language: ruby

rvm:
  - 2.2.2 # this is what 1863BFAF itself runs on

# need to be able to install packages
sudo: true

# check for presence perl, php, python, java and.. curl/wget
before_install:
  - which perl
  - which php; exit 0
  - which python; exit 0
  - which java; exit 0
  - which curl; exit 0
  - which wget; exit 0

notifications:
  email: false

bundler_args: --without test --jobs 3 --retry 3
script: bundle exec rake test reek build
